// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorites.sql

package sqlcdb

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, product_id) VALUES (?, ?)
`

type AddFavoriteParams struct {
	UserID    string `json:"user_id"`
	ProductID int64  `json:"product_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addFavorite, arg.UserID, arg.ProductID)
	return err
}

const isFavorite = `-- name: IsFavorite :one
SELECT COUNT(*) as count FROM favorites
WHERE user_id = ? AND product_id = ?
LIMIT 1
`

type IsFavoriteParams struct {
	UserID    string `json:"user_id"`
	ProductID int64  `json:"product_id"`
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isFavorite, arg.UserID, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listFavoritesByUserID = `-- name: ListFavoritesByUserID :many
SELECT user_id, product_id, created_at FROM favorites WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListFavoritesByUserID(ctx context.Context, userID string) ([]Favorite, error) {
	rows, err := q.db.QueryContext(ctx, listFavoritesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Favorite
	for rows.Next() {
		var i Favorite
		if err := rows.Scan(&i.UserID, &i.ProductID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites WHERE user_id = ? AND product_id = ?
`

type RemoveFavoriteParams struct {
	UserID    string `json:"user_id"`
	ProductID int64  `json:"product_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeFavorite, arg.UserID, arg.ProductID)
	return err
}
