// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package sqlcdb

import (
	"context"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, product_id, quantity, price_at_purchase)
VALUES (?, ?, ?, ?, ?)
RETURNING id, order_id, product_id, quantity, price_at_purchase
`

type CreateOrderItemParams struct {
	ID              string  `json:"id"`
	OrderID         string  `json:"order_id"`
	ProductID       int64   `json:"product_id"`
	Quantity        int64   `json:"quantity"`
	PriceAtPurchase float64 `json:"price_at_purchase"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtPurchase,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtPurchase,
	)
	return i, err
}

const existsOrderItemByUserAndProduct = `-- name: ExistsOrderItemByUserAndProduct :one
SELECT COUNT(*) as count FROM order_items oi
JOIN orders o ON oi.order_id = o.id
WHERE o.user_id = ? AND oi.product_id = ? AND o.status IN ('paid', 'shipped', 'delivered')
LIMIT 1
`

type ExistsOrderItemByUserAndProductParams struct {
	UserID    string `json:"user_id"`
	ProductID int64  `json:"product_id"`
}

func (q *Queries) ExistsOrderItemByUserAndProduct(ctx context.Context, arg ExistsOrderItemByUserAndProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsOrderItemByUserAndProduct, arg.UserID, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, quantity, price_at_purchase FROM order_items WHERE order_id = ?
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.PriceAtPurchase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
