// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_submissions.sql

package sqlcdb

import (
	"context"
)

const createReviewSubmission = `-- name: CreateReviewSubmission :exec
INSERT INTO review_submissions (user_id, product_id, strapi_review_id)
VALUES (?, ?, ?)
`

type CreateReviewSubmissionParams struct {
	UserID         string `json:"user_id"`
	ProductID      int64  `json:"product_id"`
	StrapiReviewID string `json:"strapi_review_id"`
}

func (q *Queries) CreateReviewSubmission(ctx context.Context, arg CreateReviewSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createReviewSubmission, arg.UserID, arg.ProductID, arg.StrapiReviewID)
	return err
}

const existsReviewSubmission = `-- name: ExistsReviewSubmission :one
SELECT COUNT(*) as count FROM review_submissions
WHERE user_id = ? AND product_id = ?
LIMIT 1
`

type ExistsReviewSubmissionParams struct {
	UserID    string `json:"user_id"`
	ProductID int64  `json:"product_id"`
}

func (q *Queries) ExistsReviewSubmission(ctx context.Context, arg ExistsReviewSubmissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsReviewSubmission, arg.UserID, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
